### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by galaxytwenty** [supercrafter333/PlotHomes#1]
Hey,

it would be nice when you can add 2 Features.

1. player cann teleport to plot without write the complete name and with strtolower
Example: 
PlayerName: SuPeRcRaFtEr333
Command: /p h super 1 or 2 ......

 2. player can Teleport to OfflinePlayer Plot
      OfflinePlayerName: Supercrafter333
      Command: /p h super 1 or 2 ......

Thx man

**Comment by supercrafter333** [comment]
Thank's for your suggestions.
I'll try to implement that in the coming versions of PlotHomes.

**Comment by galaxytwenty** [comment]
THX :)

**Comment by supercrafter333** [comment]
I can't implement this suggestion because MyPlot isn't saving player datas as lower strings.
