### ISSUE TITLE
/p h und Home probleme 

### ISSUE THREAD

**Issue by ghost** [supercrafter333/PlotHomes#2]
/p h und homes finden kein geclaimtes Plot obwohl ich 5 plots besitze 

![Screenshot_20211019-163939_Minecraft](https://user-images.githubusercontent.com/50929188/137933418-145cbfbd-641a-4d9b-aed1-1c7f40a41471.png)

**Comment by supercrafter333** [comment]
Welche Version von MyPlot verwendeste denn?

**Comment by DragonfireHD** [comment]
@supercrafter333
