### ISSUE TITLE
MyPlot 

### ISSUE THREAD

**Issue by MonoAdrian23** [supercrafter333/PlotHomes#3]
Warum machst du keine Pull und Jason addet es in MyPlot?
Pocketmine brauch doch nicht für jede Kleinigkeit ein Plugin.
MyPlot ist auch nur eine Kopie von PlotMe.
Ist doch wirklich nicht schwer.

**Comment by FlxiBoy1313** [comment]
Ich bin genau seiner Meinung, werde deswegen auch PlotChat als Pull bei MyPlot adden. Man braucht wirklich ned für jede einzelne Sache ein Plugin.

**Comment by supercrafter333** [comment]
Jason hat bereits gesagt, das er dies nicht adden wird, deshalb gab es auch das Script dafür von Jason (welches nicht mehr funktioniert hatte). Über PlotChat hat er jedoch noch nichts gesagt.
